### ISSUE TITLE
El futuro de FSN

### ISSUE THREAD

**Issue by froi** [fullstacknights/fullstacknights.github.io#10]
Estamos viendo cual es el futuro de FSN. La situación esta un poco complicada despues de que el huracan Maria azotara a PR. No obstante queremos continuar con FSN. Es una comunidad que no queremos abandonar. [Tenemos un video](https://www.youtube.com/watch?v=H-isjmWbu64) explicando esto un poco mas a fondo.

Nos gustaría saber que la comunidad opina sobre cual debería ser el futuro. ¿Qué les gustaría ver?

Dejen sus comentarios en este issue y el equipo los estara mirando.

Gracias!!!

**Comment by FutoRicky** [comment]
Hey! Pues a mi me gusta lo que han estado haciendo y me gustaria ver que continúe. En cuanto a qué me gustaría ver nuevo, pues la verdad es que el formato que tienen está chevere. Eso si, unas cervecitas nunca vienen mal 🍺  jaja (Se que no permiten alcohol en el science trust).

**Comment by froi** [comment]
Gracias @FutoRicky. La verdad es que nosotros no queremos el alchol en la actividad 😄 

Ya tenemos otros FSN. Postearemos fecha pronto :)

**Comment by ghost** [comment]
@froi Han considerado en colaboraciones con otras comunidades como GDGPR, PRPass, IncludeGirls etc? Creo las mismas se van a beneficiar por ejemplo con los recursos de grabar las sesiones al igual que ustedes ya que los temas de las mismas siempre son buenisimos pero no hay por dónde re-watch them :(

**Comment by froi** [comment]
@jrsosa Desde un comienzo no queriamos colaborar con otras comunidades, en el sentido de que organizemos un evento juntos. Hay varias razones para esto:

1. Queremos mantenernos independientes. 
  Para nosotros esto es crucial. Otros meetups estan atados a una compañía / sponsor y pensamos que eso es fantastico, solo no para nosotros.
2. Queremos permanecer flexibles en nuestras fechas. 
  Una gran parte del proceso de FSN es considerar charlas y tener sesiones de "mentoria" con los charlistas. Hacemos que ellos hagan la presentación y la vamos refinando con ellos. 
  ¿Por qué esto afecta fechas? Si no estamos satisfechos con la charla cancelamos el evento.
3. La premisa original de FSN era elevar la calidad de evento y charlas que se presentaba. Esto esta super sugeto a nuestras opiniones. No queremos imponer esto a otros meetups que ya tienen un estilo.
4. El recurso de grabación es probono. 
  El camarografo es el padre de @gcollazo y lo hace por hobbie. Hasta ahora no nos ha dicho que no pero en cualquier momento nos dice adios. Eso es algo que no controlamos y nos ha dicho que es un favor a nosotros por @gcollazo.
5. El editaje de los videos los hacemos nosotros.
  Esto se hace cuando tenemos tiempo y es afectado por 1000 y una razones. Es algo que tampoco queremos "imponerles" a otros grupos.
6. FSN cobra. Son solo $5 y todo se va cubriendo costos, pero se cobra. Es algo que no vamos a quitar y entendemos que no es el modus operandi de otros meetups.

Dicho esto no significa que no tomemos tu sugerencia. Voy a traerla al equipo para discutirla.

Gracias!!!

**Comment by gcollazo** [comment]
@jrsosa estoy de acuerdo con todo lo que dice @froi arriba. Dicho esto pienso que tu punto de involucrar a otros grupos es posible. Creo que la idea de hacer un `FSN IncludeGirls Edition` o algo así suena bien.

Sobre el tema de los vídeos he estado pensando en que FSN debe comprar un kit simple de grabación de vídeos. Con la ayuda de mi padre podemos dar un tutorial de como usar el equipo y editar los vídeos y hacer el equipo disponible a todos los grupos que lo necesiten. De esta forma logramos que mas eventos se graben. Creo que esto sería un WIN para toda la comunidad.

Volviendo al tema original de colaboración. De mi parte creo que lo único que tendría que hacer un grupo es:

* Someter charlas que se amolden al formato de FSN. En el site hay un form que está disabled pero @froi cuando pueda va a enable 😉
* Contactarnos por aquí mismo o por donde prefieran y dejarnos saber que quieren ayudar a organizar una "edición especial" de FSN
* Tener una conversación sobre quien hace que. El equipo de FSN tiene el proceso super planchado y documentado. Es fácil delegar.
* Los conferenciantes deben pasar por el proceso de feedback, ensayo, fix, etc...
* Coordinar la promo del evento en conjunto

Seguramente se me quedan algunas cosas que alguien del equipo mencionará pero creo que sto sería el camino más simple para lograr una colaboración. También esos grupos pueden sugerir como hacer una colaboración.

**Comment by ghost** [comment]
Super, gracias a todos

**Comment by froi** [comment]
Cerrando por inactividad y tiempo.
