### ISSUE TITLE
Videos section not working

### ISSUE THREAD

**Issue by FutoRicky** [fullstacknights/fullstacknights.github.io#16]
Me huele a s3 env variables incorrectos. Localmente funciona.

![screen shot 2018-03-13 at 3 01 01 pm](https://user-images.githubusercontent.com/7366284/37363894-70012e80-26cf-11e8-8006-8d99e38a5707.png)

**Comment by froi** [comment]
Yeah >:(

Gracias por crear el issue. Will look into it. :)

**Comment by jpadilla** [comment]
I don't think this is still an issue.
