### ISSUE TITLE
Problem loading videos on Chrome

### ISSUE THREAD

**Issue by gcollazo** [fullstacknights/fullstacknights.github.io#7]
![screen shot 2017-06-05 at 8 04 53 am](https://cloud.githubusercontent.com/assets/61048/26783368/cb12f548-49c5-11e7-914c-9db3288529f3.png)

http://www.fullstacknights.com/fsn/videos/2017/06/04/fullstack-nights-v7-videos/

**Comment by ghost** [comment]
Thanks for the heads up. I'll look at it during the day.
